name = "newsnow"
compatibility_date = "2024-10-04"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

[env.production]
vars = { NODE_ENV = "production", ENABLE_CACHE = "true", INIT_TABLE = "true" }

# 数据库配置
[[env.production.d1_databases]]
binding = "DB"
database_name = "database1"
database_id = "233ef401-7a7f-4c49-ae68-6b6997458f05"

# KV 存储配置（用于缓存）
[[env.production.kv_namespaces]]
binding = "CACHE"
id = "e1ccb58f79c44545a03d775458b6168f"

[env.preview]
vars = { NODE_ENV = "preview", ENABLE_CACHE = "false" }

# 预览环境的数据库配置（暂时注释掉）
# [[env.preview.d1_databases]]
# binding = "DB"
# database_name = "newsnow-db-preview"
# database_id = "your-preview-database-id-here"
